# Generated by Django 4.2.7 on 2023-11-30 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='tiempo',
            field=models.DurationField(),
        ),
    ]
