# Generated by Django 4.2.5 on 2023-10-26 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('model_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Emplado',
            new_name='Empleado',
        ),
    ]
